spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:distribuidora;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
